# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hayden Westbrook
tagline:          'My portfolio'
url:              https://haydentwestbrook.github.io
baseurl:          /

author:
  name:           'Hayden Westbrook'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/haydentwestbrook

linkedIn: https://www.linkedin.com/in/hayden-westbrook-466a76177/
email: haydentwestbrook@gmail.com
phone: 480-495-7811

resume: https://docs.google.com/document/d/1I9ZCOJ4Zilm7hfnn8KoE_pGZJ8IDHqmjk3gh2RHwAhA/export?format=pdf